### ISSUE TITLE
Getting a few errors

### ISSUE THREAD

**Issue by InushaDeSilva** [mcoop320/img2vid#4]
Any idea why? 
![IMG_20210626_202607](https://user-images.githubusercontent.com/74726248/123517045-c3aca780-d6bc-11eb-8430-5e11b7a2279f.jpg)

**Comment by advplyr** [comment]
Make sure you include the output field in your payload.
`output: "./output.mp4"`

**Comment by InushaDeSilva** [comment]
It's already included

**Comment by InushaDeSilva** [comment]
Sinc since it keeps failing I simplified my input to this but still doesn't work. Says the filter xfade is not available even though I'm on the latest version of ubuntu and ffmpeg 
![IMG_20210626_234106](https://user-images.githubusercontent.com/74726248/123522027-1d6e9b00-d6d8-11eb-952c-74ec052f78ec.jpg)

**Comment by InushaDeSilva** [comment]
> Sinc since it keeps failing I simplified my input to this but still doesn't work. Says the filter xfade is not available even though I'm on the latest version of ubuntu and ffmpeg
> ![IMG_20210626_234106](https://user-images.githubusercontent.com/74726248/123522027-1d6e9b00-d6d8-11eb-952c-74ec052f78ec.jpg)

@mcoop320

**Comment by advplyr** [comment]
Type `ffmpeg -filters` in the terminal and see if "xfade" and "xfade_opencl" is in that list.

**Comment by InushaDeSilva** [comment]
> Type `ffmpeg -filters` in the terminal and see if "xfade" and "xfade_opencl" is in that list.

![IMG_20210627_050753](https://user-images.githubusercontent.com/74726248/123528539-a9e38280-d705-11eb-9dd9-84e81133465d.jpg)
It seems to be there although can't find the 2nd one you said

**Comment by InushaDeSilva** [comment]
![IMG_20210627_053308](https://user-images.githubusercontent.com/74726248/123528913-2fb4fd00-d709-11eb-85df-cf3009a36b86.jpg)
Another error

**Comment by advplyr** [comment]
If your input image is not 640x480 or whatever width/height you specify in the payload, then it will fail.

You can add `forceScale: true` to your payload and it will scale the image for you.

**Comment by InushaDeSilva** [comment]
> If your input image is not 640x480 or whatever width/height you specify in the payload, then it will fail.
> 
> You can add `forceScale: true` to your payload and it will scale the image for you.

OK I added that in but still didn't work, prints these 3 errors

**Comment by InushaDeSilva** [comment]
![IMG_20210627_110218](https://user-images.githubusercontent.com/74726248/123533968-293d7a00-d737-11eb-93e8-59e6530a0631.jpg)

**Comment by InushaDeSilva** [comment]
> If your input image is not 640x480 or whatever width/height you specify in the payload, then it will fail.
> 
> You can add `forceScale: true` to your payload and it will scale the image for you.

OK so I added " " in between the complex filter options and now I get this... 
![IMG_20210627_151252](https://user-images.githubusercontent.com/74726248/123540004-49cafb80-d75a-11eb-99d0-b7c65aeb4f5a.jpg)

**Comment by InushaDeSilva** [comment]
![IMG_20210627_154711](https://user-images.githubusercontent.com/74726248/123540903-f60ee100-d75e-11eb-8c53-c6fe3b1b01f6.jpg)
When trying to add 2 videos

Yes I marked the 'isVideo' and tag true

**Comment by InushaDeSilva** [comment]
> ![IMG_20210627_154711](https://user-images.githubusercontent.com/74726248/123540903-f60ee100-d75e-11eb-8c53-c6fe3b1b01f6.jpg)
> When trying to add 2 videos
> 
> Yes I marked the 'isVideo' and tag true

Seems like there are 3 extras in the xfade framerate

**Comment by advplyr** [comment]
Looks like your input videos may need to be adjusted to have the same frame rate.

I'm assuming you were able to get it working using only pictures?

**Comment by InushaDeSilva** [comment]
> Looks like your input videos may need to be adjusted to have the same frame rate.
> 
> I'm assuming you were able to get it working using only pictures?

Yes it worked for pictures but it doesn't follow the time I enter in the feild and only appear for 1s each, but at least there is an output unlike for the videos

**Comment by InushaDeSilva** [comment]
> Looks like your input videos may need to be adjusted to have the same frame rate.
> 
> I'm assuming you were able to get it working using only pictures?

Could you tell me how to do that? The framerate thing

**Comment by advplyr** [comment]
You can use Ffmpeg. See the first example here: https://trac.ffmpeg.org/wiki/ChangingFrameRate

**Comment by InushaDeSilva** [comment]
> You can use Ffmpeg. See the first example here: https://trac.ffmpeg.org/wiki/ChangingFrameRate

So I have to turn my videos to 30000fps?😳 Combibe then back again 30 if I want to?

**Comment by TentacleSama4254** [comment]
If that's the case 
![Uploading IMG_20210627_164356.jpg…]()

**Comment by TentacleSama4254** [comment]
![IMG_20210627_164356](https://user-images.githubusercontent.com/74726248/123542376-f612df00-d766-11eb-8af6-49108cdb2a54.jpg)

**Comment by InushaDeSilva** [comment]
Oof 
![IMG_20210627_164711](https://user-images.githubusercontent.com/74726248/123542442-5a35a300-d767-11eb-843f-0671b9429cd7.jpg)

**Comment by advplyr** [comment]
No, the framerate was 30000/1001 which is roughly 29.97 fps.

You need to copy paste your actual commands in here because most error messages can be caused by many different things.

**Comment by InushaDeSilva** [comment]
> No, the framerate was 30000/1001 which is roughly 29.97 fps.
> 
> You need to copy paste your actual commands in here because most error messages can be caused by many different things.

Bingo! I added -r 30000/1001 in front of each input and there was an output, But the issue is each video is still 1s long eventhough I specified the length of each video in the parameters

**Comment by TentacleSama4254** [comment]
OK got it working but the subtitles don't seem to work @mcoop320

**Comment by advplyr** [comment]
You'll have to post your input. First try simple captions with only text, start, and end.
Check the captionsDemo.js file for example.

**Comment by InushaDeSilva** [comment]
OK one last thing, when Im adding videos did u write the code to copy the audio to the final video too or do I need to add them separately?
@mcoope31 @mcoop320

**Comment by advplyr** [comment]
It will not pull in the audio from videos. If you only have 1 video that you want the audio from, you can add:

`audio: "./videofile.mp4"`

to your input and it will use the audio from that video. Only 1 audio file is accepted.

**Comment by InushaDeSilva** [comment]
> It will not pull in the audio from videos. If you only have 1 video that you want the audio from, you can add:
> 
> `audio: "./videofile.mp4"`
> 
> to your input and it will use the audio from that video. Only 1 audio file is accepted.

Thx m8
