### ISSUE TITLE
Xfade

### ISSUE THREAD

**Issue by InushaDeSilva** [mcoop320/img2vid#5]
i recently had to switch systems with that after rebuilding ffmpeg , the XFADE filter was lost (again) 

could you please provide a good solution to get the filter beacuse without xfade none of the transitions would run

**Comment by InushaDeSilva** [comment]
![image](https://user-images.githubusercontent.com/74726248/125748830-cb594ec6-bcfb-4c61-9d30-449b309c21ae.png)

**Comment by advplyr** [comment]
Check the version of Ffmpeg you installed. Xfade is included in Ffmpeg as of v4.3.0.

See:
http://ffmpeg.org/#:~:text=Games%20ASF%20demuxer-,xfade%20video%20filter,-xfade_opencl%20filter
